module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring River',
    'Rock Bridge',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Cottonwood',
    'Maple Tree',
    'Misty',
    'Windy',
    'Hooting Owl',
    'Elk',
    'Grizzly',
    'Ocean',
    'Seashine',
    'Big Sky',
    'Clear Sky',
    'Starry Sky',
    'Sandy',
    'Dusty',
    'Diamond',
    'Crystal',
    'Green',
    'Blue',
    'Red',
    'Purple',
    'Golden',
    'Sunshine',
    'Lazy',
    'Peace',
    'Lovers',
    'Friendly',
    'Horseshoe',
    'Cowboy',
    'Tranquil',
    'Whispering Winds',
    'Krakoa',
    'Majestic',
    'Sparkling',
    'Big Piney',
    'Hellbender',
    'Raccoon',
    'Bigfoot',
    'Sasquatch',
    'Mothman',
    'Dogman',
    'Wood Booger',
    'Wild',
    'Woody'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Mountain',
    'Hill',
    'Hills',
    'Lake',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Campground',
    'Campground',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Rivers',
    'Streams',
    'Creeks',
    'Creek',
    'Bend',
    'Bay',
    'Brooke',
    'Spring',
    'Springs',
    'Bayshore',
    'Shore',
    'Shores',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Summer Camp',
    'Fat Camp',
    'Retreat',
    'Outdoor Outfitters',
    'Cliff',
    'Cliffs',
    'Hollow',
    'Holler',
    'Bluff',
    'Bluffs',
    'Falls',
    'Valley',
    'Beach',
    'Outdoors',
    'Resort',
    'Bible Camp',
    'Quran Summer Camp',
    'Buddhist Retreat',
    'Wilderness'
]